version: "3.8"
services:
  php74_collection_expansion:
    container_name: php74_collection_expansion
    build:
      context: .
      dockerfile: ./.docker/dockerfile/PHP74_Dockerfile
    volumes:
      - .:/var/www/html
    init: true
    # restart: unless-stopped
    command: ./.docker/command/test.sh

  php80_collection_expansion:
    container_name: php80_collection_expansion
    build:
      context: .
      dockerfile: ./.docker/dockerfile/PHP80_Dockerfile
    volumes:
      - .:/var/www/html
    init: true
    # restart: unless-stopped
    command: ./.docker/command/test.sh
    depends_on:
      - php74_collection_expansion

  php81_collection_expansion:
    container_name: php81_collection_expansion
    build:
      context: .
      dockerfile: ./.docker/dockerfile/PHP81_Dockerfile
    volumes:
      - .:/var/www/html
    init: true
    # restart: unless-stopped
    command: ./.docker/command/test.sh
    depends_on:
      - php80_collection_expansion

  php82_collection_expansion:
    container_name: php82_collection_expansion
    build:
      context: .
      dockerfile: ./.docker/dockerfile/PHP82_Dockerfile
    volumes:
      - .:/var/www/html
    init: true
    # restart: unless-stopped
    command: ./.docker/command/test.sh
    depends_on:
      - php81_collection_expansion
